module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "docs",
        "style",
        "refactor",
        "perf",
        "test",
        "build",
        "ci",
        "chore",
        "revert",
        "wip",
      ],
    ],
    "scope-enum": [
      2,
      "always",
      [
        "core",
        "api",
        "config",
        "deps",
        "ci",
        "supabase",
        "db",
        "rls",
        "worker",
        "jobs",
        "ui",
        "components",
        "pages",
        "layout",
        "styles",
        "auth",
        "security",
        "seo",
        "geo",
        "reporting",
        "scope",
        "docs",
        "test",
        "qa",
      ],
    ],
    "subject-max-length": [2, "always", 100],
    "body-max-line-length": [0],
  },
};
